[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.18.4",
    "crewai>=1.11.0",
    "fastapi>=0.135.1",
    "langdetect>=1.0.9",
    "psycopg2-binary>=2.9.11",
    "pyjwt>=2.12.1",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.42.0",
]
