"""add tokens_usage field

Revision ID: 4155b56d7dba
Revises: c024f2bd9357
Create Date: 2026-03-20 22:25:00.600349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4155b56d7dba'
down_revision: Union[str, Sequence[str], None] = 'c024f2bd9357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tokens_usage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tokens_usage')
    # ### end Alembic commands ###
