"""update chats

Revision ID: c024f2bd9357
Revises: 02be2c7b0132
Create Date: 2026-03-20 15:31:00.519351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c024f2bd9357'
down_revision: Union[str, Sequence[str], None] = '02be2c7b0132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_thinking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_thinking')
    # ### end Alembic commands ###
